name: Manually run the GitHubStats application
on:
  workflow_dispatch: # Manual workflow trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x

    - name: Restore Dependencies
      run: cd GitHubStats && dotnet restore

    - name: Build
      env:
          SecretTest: ${{ secrets.SecretTest }} # Using a temporary "secret" here for testing purposes
      run: cd GitHubStats && ls && dotnet build --configuration Action

    - name: Run Console App
      env:
          SecretTest: ${{ secrets.SecretTest }} # Using a temporary "secret" here for testing purposes (not sure if it's needed here too - testing')
      run: cd GitHubStats && dotnet run --project ConsoleApplication --configuration Action