name: Manually run the GitHubStats application
on:
  workflow_dispatch: # Manual workflow trigger

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SECRET_TEST: ${{ secrets.SECRET_TEST }} # Testing using an example GitHub secret

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x

    - name: Restore Dependencies
      run: cd GitHubStats && dotnet restore
        
    - name: Build
      run: cd GitHubStats && ls && dotnet build --configuration Action
      env:
          SecretTest: ${{ secrets.SECRET_TEST }}

    - name: Run Console App
      run: cd GitHubStats && dotnet run --project ConsoleApplication --configuration Action
      env:
          SecretTest: ${{ secrets.SECRET_TEST }} #not sure about this, but having issues with this secret...