name: Manually run the GitHubStats application
on:
  workflow_dispatch: # Manual workflow trigger

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SecretTest: ${{ secrets.SECRET_TEST }} # Tmeporary secret

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x

    - name: Restore Dependencies
      run: cd GitHubStats && dotnet restore

    - name: Print test secret value 
      run:  |
        echo "SecretTest value: ${SecretTest}"
        
    - name: Build
      run: cd GitHubStats && ls && dotnet build --configuration Action /p:SecretTest="${SecretTest}"

    - name: Run Console App
      run: cd GitHubStats && dotnet run --project ConsoleApplication --configuration Action 